sudo: false # docker-based container

language: python

python:
  - 3.6

scala:
  - 2.11.2

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/tmp

before_script:
  - wget https://github.com/sbt/sbt/releases/download/v1.0.3/sbt-1.0.3.zip -O tmp/sbt-1.0.3.zip
  - unzip tmp/sbt-1.0.3.zip -d tmp
  - cp tmp/sbt/bin/sbt-launcher.jar $HOME/.sbt/launchers/1.0.3/

script:
  - make build_compiler
  - make test
