sudo: false # docker-based container

language: python

python:
  - 3.6

scala:
  - 2.11.2

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/tmp

before_script:
  - wget https://github.com/sbt/sbt/releases/download/v1.0.3/sbt-1.0.3.zip -O $HOME/tmp/sbt-1.0.3.zip
  - rm -rf $HOME/tmp/*
  - unzip $HOME/tmp/sbt-1.0.3.zip -d $HOME/tmp
  - find $HOME/tmp -name sbt-launcher.jar -exec cp {} $HOME/.sbt/launchers/1.0.3/ \;
  - ls -l $HOME/.sbt/launchers/1.0.3/

script:
  - make build_compiler
  - make test
